# Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
# the License. A copy of the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
# and limitations under the License.

AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CodeKey:
    Type: String
    Description: >-
      The key that the lambda function code has been uploaded to
Resources:
  ## The main S3 bucket. This must use the same logical resource ID as bootstrap.yaml.
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 1
            Status: Enabled
            Prefix: "AWSLogs/"
      VersioningConfiguration:
        Status: Enabled

  ## The sqs queue we will deliver encrypted messages to
  SQSQueue:
    Type: 'AWS::SQS::Queue'

  ## API Gateway Roles
  ApiCloudwatchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com

  ## API Gateway related resources
  RestAPI:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      BinaryMediaTypes:
      # TODO: Remove this and use modeled JSON structures?
        - '*/*'
      Name: !Ref 'AWS::StackName'
  RestAPICloudWatch:
    Type: 'AWS::ApiGateway::Account'
    Properties:
      CloudWatchRoleArn: !GetAtt ApiCloudwatchRole.Arn
    DependsOn:
      - RestAPI
  RestAPIRootGET:
  # Handle a GET on the root by proxying through to our index.html static asset
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: GET
        PassthroughBehavior: WHEN_NO_MATCH
        Type: HTTP_PROXY
        Uri: !Sub https://${S3Bucket}.s3.${AWS::Region}.amazonaws.com/static-assets/index.html
      ResourceId: !GetAtt RestAPI.RootResourceId
      RestApiId: !Ref RestAPI
    DependsOn:
      - RestAPI
  RestAPIRootPost:
  # Handle POSTs to the root by delegating to our Java lambda code
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        PassthroughBehavior: WHEN_NO_MATCH
        Type: AWS_PROXY
        Uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunc.Arn}/invocations
      ResourceId: !GetAtt RestAPI.RootResourceId
      RestApiId: !Ref RestAPI

  # Configuration for the /static path - we delegate requests under this path directly through to S3.
  RestAPIStaticResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !GetAtt RestAPI.RootResourceId
      PathPart: 'static'
  RestAPIStaticWildcardResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !Ref RestAPIStaticResource
      PathPart: '{path+}'
  RestAPIStaticGET:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      RequestParameters:
        method.request.path.path: true
      Integration:
        RequestParameters:
          integration.request.path.path: method.request.path.path
        IntegrationHttpMethod: ANY
        PassthroughBehavior: WHEN_NO_MATCH
        Type: HTTP_PROXY
        Uri: !Sub https://${S3Bucket}.s3.${AWS::Region}.amazonaws.com/static-assets/{path}
      ResourceId: !Ref RestAPIStaticWildcardResource
      RestApiId: !Ref RestAPI

  # Configuration for /logs. We use this to redirect to the cloudwatch logs console. To avoid needing to involve the
  # java handler (which has higher startup times and would necessitate using the proxy handler mode), this is
  # implemented with a separate, simple lambda function.
  RestAPILogsResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !GetAtt RestAPI.RootResourceId
      PathPart: 'logs'
  RestAPILogsGET:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        PassthroughBehavior: WHEN_NO_MATCH
        Type: AWS_PROXY
        Uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LogsConsoleRedirectLambdaFunc.Arn}/invocations
      ResourceId: !Ref RestAPILogsResource
      RestApiId: !Ref RestAPI

  LogsConsoleRedirectLambdaFunc:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        # This is not actually a ZIP file, but cloudformation names it as such.
        ZipFile: !Sub |
          var querystring = require("querystring");
          var arn = "${KMSKey.Arn}";
          var query = "{ $.resources[0].ARN = " + JSON.stringify(arn) + " }";
          var encodedquery = querystring.escape(query);
          var kmslocation = "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}" +
                         "#logEventViewer:group=${CloudtrailLogGroup};filter=" + encodedquery;

          var lambdalocation = "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}" +
                         "#logEventViewer:group=/aws/lambda/${LambdaFunc}";
          exports.redirect = function(event, context, callback) {
              console.log('Received event: ' + JSON.stringify(event));

              var location = kmslocation;
              if (event.queryStringParameters && event.queryStringParameters.type === 'lambda') {
                  location = lambdalocation;
              }

              response = { isBase64Encoded: false,
                           statusCode: 303,
                           headers: {
                               "Location": location
                           },
                           body: "Redirecting to the cloudwatch logs console..."
              };
              callback(null, response);
          }
      Handler: index.redirect
      MemorySize: 128
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs6.10
      Timeout: 5
  RedirectPermissions:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref LogsConsoleRedirectLambdaFunc
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${RestAPI}/*

  # API gateway stage and deployment configuration. We use a new logical ID for the deployment each time we update the
  # CF template; this is because the deployment captures the current state of the resource and method tree at the time
  # it is created, so to reflect any changes it needs to be recreated and the new deployment bound to the stage.
  ApiStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      RestApiId: !Ref RestAPI
      DeploymentId: !Ref ApiDeployment%UNIQUE%
      StageName: test
      MethodSettings:
        - ResourcePath: /*
          HttpMethod: '*'
          DataTraceEnabled: true
          LoggingLevel: INFO

  ApiDeployment%UNIQUE%:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref RestAPI
      Description: Example deployment
    DependsOn:
    # This DependsOn relation ensures that we don't create the deployment before we finish configuring the resources;
    # otherwise the deployment might capture an incomplete configuration.
      - RestAPIRootGET
      - RestAPIRootPost
      - RestAPIStaticGET
      - RestAPILogsGET

  ## KMS key configuration
  KMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: !Sub "KMS key for use in the cloudformation stack ${AWS::StackName}" 
      KeyPolicy:
        Version: 2012-10-17
        Id: key-policy
        Statement:
          - Sid: Allow account-level IAM policies to apply to the key
            Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Action:
              - '*'
            Resource: '*'

  ## This alias isn't actually used, but makes the purpose of the key clearer in the console.
  KMSAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Join 
        - ''
        - - alias/
          - !Ref 'AWS::StackName'
          - '-key'
      TargetKeyId: !Ref KMSKey

  ## Main backend application lambda function configuration
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  IAMPolicyWrite:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
        - !Ref LambdaRole
      PolicyName: WritePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: !GetAtt SQSQueue.Arn
            Action: 
              - "sqs:GetQueueUrl"
              - "sqs:SendMessage*"
              - "sqs:GetQueueUrl"
              - "sqs:ReceiveMessage*"
              - "sqs:ChangeMessageVisibility*"
              - "sqs:DeleteMessage*"
          - Effect: Allow
            Resource: !GetAtt KMSKey.Arn
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:GenerateDataKey"

  LambdaFunc:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref CodeKey
      Handler: example.EntryPoint
      ## We don't need this much memory, but setting a high memorysize means we get more CPU allocated, which reduces
      ## startup times.
      MemorySize: 1536
      Role: !GetAtt LambdaRole.Arn
      Runtime: java8
      Timeout: 30
      Environment:
        Variables:
          kms_key_id: !GetAtt KMSKey.Arn
          queue_url: !Ref SQSQueue
          use_cache: true
          log_group_name: !Ref CloudtrailLogGroup

# To use this Python Lambda Function:
# 1. Use "mvn deploy" to create the S3 bucket and all other resources
# 2. Either comment out the above "LambdaFunc" resource or change its name
# 3. Uncomment the below "LambdaFunc" resource
# 4. Use python-build-remote.sh to build the Python package and upload it to the S3 bucket
# 5. Update the S3ObjectVersion value below with the value you received from python-build-remote.sh
# 6. Use "mvn deploy" to update the stack with the new Lambda Function
#
# To apply any updates to the Python Lambda Function, repeat steps 4, 5, and 6.
#
#  LambdaFunc:
#    Type: 'AWS::Lambda::Function'
#    Properties:
#      Code:
#        S3Bucket: !Ref S3Bucket
#        S3Key: reinvent_sid345_python.zip
#        S3ObjectVersion: 1qWn1OjoiAs4jv03EX3hCylttOEh7TIb
#      Handler: reinvent_sid345.handler.lambda_handler
#      ## We don't need this much memory, but setting a high memorysize means we get more CPU allocated, which reduces
#      ## startup times.
#      MemorySize: 1536
#      Role: !GetAtt LambdaRole.Arn
#      Runtime: python3.6
#      Timeout: 30
#      Environment:
#        Variables:
#          kms_key_id: !GetAtt KMSKey.Arn
#          queue_url: !Ref SQSQueue
#          use_cache: true
#          log_group_name: !Ref CloudtrailLogGroup

  MainAppPermissions:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref LambdaFunc
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${RestAPI}/*

# Configure a cloudtrail to deliver via cloudwatch logs; having them in CWlogs makes it easier to search for events
# related to our KMS key.
  Cloudtrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      IsMultiRegionTrail: false # We only care about demo resources in the same region
      IsLogging: true
      CloudWatchLogsLogGroupArn: !GetAtt CloudtrailLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt CloudtrailRole.Arn
      # an S3 bucket is still required, even when using CWlogs delivery
      S3BucketName: !Ref S3Bucket
    DependsOn:
     # We need to wait for the various IAM policies to be configured, as CW logs will validate these policies when the
     # trail is created, and fail the trail creation if they are not configured appropriately.
      - CloudtrailBucketPolicy
      - CloudtrailRolePolicy

  CloudtrailRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: "sts:AssumeRole"
            Effect: Allow
            Principal: { "Service": "cloudtrail.amazonaws.com" }

  CloudtrailRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles: [!Ref CloudtrailRole]
      PolicyName: CloudtrailPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PutLogs
            Effect: Allow
            Action: ["logs:CreateLogStream", "logs:PutLogEvents"]
            Resource: !GetAtt CloudtrailLogGroup.Arn

  CloudtrailLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      RetentionInDays: 1

  CloudtrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Sid: AclCheck
            Effect: Allow
            Principal: { Service: cloudtrail.amazonaws.com }
            Action: s3:GetBucketAcl
            Resource: !GetAtt S3Bucket.Arn
          - Sid: CloudtrailWrite
            Effect: Allow
            Principal: { Service: cloudtrail.amazonaws.com }
            Action: s3:PutObject
            Resource: !Sub "${S3Bucket.Arn}/AWSLogs/${AWS::AccountId}/*"
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"
