# Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
# the License. A copy of the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
# and limitations under the License.

AWSTemplateFormatVersion: 2010-09-09
%PARAMETERS%
Resources:
  ## The main S3 bucket. This must use the same logical resource ID as bootstrap.yaml.
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 1
            Status: Enabled
            Prefix: "AWSLogs/"
      VersioningConfiguration:
        Status: Enabled

  ## The sqs queue we will deliver encrypted messages to
  SQSQueue:
    Type: 'AWS::SQS::Queue'

  ## API Gateway related resources
  RestAPI:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      BinaryMediaTypes:
        - '*/*'
      Name: !Ref 'AWS::StackName'
  RestAPICloudWatch:
    Type: 'AWS::ApiGateway::Account'
    Properties:
      CloudWatchRoleArn: !ImportValue "busy-engineers-workshop-ApiGatewayCloudwatchRole"
    DependsOn:
      - RestAPI
  RestAPIRootGET:
  # Handle a GET on the root by proxying through to our index.html static asset
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: GET
        PassthroughBehavior: WHEN_NO_MATCH
        Type: HTTP_PROXY
        Uri: !Sub https://${S3Bucket}.s3.${AWS::Region}.amazonaws.com/static-assets/index.html
      ResourceId: !GetAtt RestAPI.RootResourceId
      RestApiId: !Ref RestAPI
    DependsOn:
      - RestAPI
  RestAPIRootPost:
  # Handle POSTs to the root by delegating to our Java lambda code
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        PassthroughBehavior: WHEN_NO_MATCH
        Type: AWS_PROXY
        Uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunc.Arn}/invocations
      ResourceId: !GetAtt RestAPI.RootResourceId
      RestApiId: !Ref RestAPI

  # Configuration for the /static path - we delegate requests under this path directly through to S3.
  RestAPIStaticResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !GetAtt RestAPI.RootResourceId
      PathPart: 'static'
  RestAPIStaticWildcardResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !Ref RestAPIStaticResource
      PathPart: '{path+}'
  RestAPIStaticGET:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      RequestParameters:
        method.request.path.path: true
      Integration:
        RequestParameters:
          integration.request.path.path: method.request.path.path
        IntegrationHttpMethod: ANY
        PassthroughBehavior: WHEN_NO_MATCH
        Type: HTTP_PROXY
        Uri: !Sub https://${S3Bucket}.s3.${AWS::Region}.amazonaws.com/static-assets/{path}
      ResourceId: !Ref RestAPIStaticWildcardResource
      RestApiId: !Ref RestAPI

  # Configuration for /logs. We use this to redirect to the cloudwatch logs console. To avoid needing to involve the
  # java handler (which has higher startup times and would necessitate using the proxy handler mode), this is
  # implemented with a separate, simple lambda function.
  RestAPILogsResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !GetAtt RestAPI.RootResourceId
      PathPart: 'logs'
  RestAPILogsGET:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        PassthroughBehavior: WHEN_NO_MATCH
        Type: AWS_PROXY
        Uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LogsConsoleRedirectLambdaFunc.Arn}/invocations
      ResourceId: !Ref RestAPILogsResource
      RestApiId: !Ref RestAPI

  LogsConsoleRedirectLambdaFunc:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        # This is not actually a ZIP file, but cloudformation names it as such.
        ZipFile: !Sub |
          var querystring = require("querystring");
          var arn = "${KMSKey.Arn}";
          var query = "{ $.resources[0].ARN = " + JSON.stringify(arn) + " }";
          var encodedquery = querystring.escape(query);
          var kmslocation = "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}" +
                         "#logEventViewer:group=${CloudtrailLogGroup};filter=" + encodedquery;

          var lambdalocation = "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}" +
                         "#logEventViewer:group=/aws/lambda/${LambdaFunc}";
          exports.redirect = function(event, context, callback) {
              console.log('Received event: ' + JSON.stringify(event));

              var location = kmslocation;
              if (event.queryStringParameters && event.queryStringParameters.type === 'lambda') {
                  location = lambdalocation;
              }

              response = { isBase64Encoded: false,
                           statusCode: 303,
                           headers: {
                               "Location": location
                           },
                           body: "Redirecting to the cloudwatch logs console..."
              };
              callback(null, response);
          }
      Handler: index.redirect
      MemorySize: 128
      Role: !ImportValue "busy-engineers-workshop-LambdaRole"
      Runtime: nodejs8.10
      Timeout: 5
  RedirectPermissions:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref LogsConsoleRedirectLambdaFunc
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${RestAPI}/*

  # API gateway stage and deployment configuration. We use a new logical ID for the deployment each time we update the
  # CF template; this is because the deployment captures the current state of the resource and method tree at the time
  # it is created, so to reflect any changes it needs to be recreated and the new deployment bound to the stage.
  ApiStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      RestApiId: !Ref RestAPI
      DeploymentId: !Ref ApiDeployment%UNIQUE%
      StageName: test
      MethodSettings:
        - ResourcePath: /*
          HttpMethod: '*'
          DataTraceEnabled: true
          LoggingLevel: INFO

  ApiDeployment%UNIQUE%:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref RestAPI
      Description: Example deployment
    DependsOn:
    # This DependsOn relation ensures that we don't create the deployment before we finish configuring the resources;
    # otherwise the deployment might capture an incomplete configuration.
      - RestAPIRootGET
      - RestAPIRootPost
      - RestAPIStaticGET
      - RestAPILogsGET

  ## KMS key configuration
  KMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: !Sub "KMS key for use in the cloudformation stack ${AWS::StackName}"
      KeyPolicy:
        Version: 2012-10-17
        Id: key-policy
        Statement:
          - Sid: Allow account-level IAM policies to apply to the key
            Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Action:
              - '*'
            Resource: '*'

  ## This alias isn't actually used, but makes the purpose of the key clearer in the console.
  KMSAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Join
        - ''
        - - alias/
          - !Ref 'AWS::StackName'
          - '-key-us-east-2'
      TargetKeyId: !Ref KMSKey

  LambdaFunc:
    Type: 'AWS::Lambda::Function'
    Properties:
      %LAMBDACONFIG%
      ## We don't need this much memory, but setting a high memorysize means we get more CPU allocated, which reduces
      ## startup times.
      MemorySize: 1536
      Role: !ImportValue "busy-engineers-workshop-LambdaRole"
      Runtime: python3.6
      Timeout: 30
      Environment:
        Variables:
          kms_key_id: !GetAtt KMSKey.Arn
          queue_url: !Ref SQSQueue
          use_cache: true
          log_group_name: !Ref CloudtrailLogGroup

  MainAppPermissions:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref LambdaFunc
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${RestAPI}/*

# Configure a cloudtrail to deliver via cloudwatch logs; having them in CWlogs makes it easier to search for events
# related to our KMS key.
  Cloudtrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      IsMultiRegionTrail: false # We only care about demo resources in the same region
      IsLogging: true
      CloudWatchLogsLogGroupArn: !GetAtt CloudtrailLogGroup.Arn
      CloudWatchLogsRoleArn: !ImportValue "busy-engineers-workshop-CloudtrailRole"
      # an S3 bucket is still required, even when using CWlogs delivery
      S3BucketName: !Ref S3Bucket
    DependsOn:
     # We need to wait for the various IAM policies to be configured, as CW logs will validate these policies when the
     # trail is created, and fail the trail creation if they are not configured appropriately.
      - CloudtrailBucketPolicy

  CloudtrailLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      RetentionInDays: 1

  CloudtrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AclCheck
            Effect: Allow
            Principal: { Service: cloudtrail.amazonaws.com }
            Action: s3:GetBucketAcl
            Resource: !GetAtt S3Bucket.Arn
          - Sid: CloudtrailWrite
            Effect: Allow
            Principal: { Service: cloudtrail.amazonaws.com }
            Action: s3:PutObject
            Resource: !Sub "${S3Bucket.Arn}/AWSLogs/${AWS::AccountId}/*"
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"

  CustomerManagedKeyCreateLambdaFunc:
    Type: 'AWS::Lambda::Function'
    Properties:
      %RESOURCECONFIG%
      MemorySize: 1536
      Role: !ImportValue "busy-engineers-workshop-LambdaRole"
      Runtime: python3.6
      Timeout: 30

  CreateCustomerManagedKey2:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt CustomerManagedKeyCreateLambdaFunc.Arn
      Region: "us-west-2"
      Alias: !Join
        - ''
        - - alias/
          - !Ref 'AWS::StackName'
          - '-key-us-west-2'
      Role: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"